//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.api.Properties.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! vui lòng liên hệ với MISA..
        /// </summary>
        public static string MISA_Error {
            get {
                return ResourceManager.GetString("MISA.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin key phải kiểm tra trùng hay không trước.
        /// </summary>
        public static string MISA_Error_Dev_DuplicateFiled {
            get {
                return ResourceManager.GetString("MISA.Error.Dev.DuplicateFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cần thiết phải validate cho chuẩn OK.
        /// </summary>
        public static string MISA_Error_Dev_InvalidField {
            get {
                return ResourceManager.GetString("MISA.Error.Dev.InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin quan trọng phải check xem null hay không đã chứ.
        /// </summary>
        public static string MISA_Error_Dev_NullField {
            get {
                return ResourceManager.GetString("MISA.Error.Dev.NullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Entity của bạn bị trùng rồi thì phải.
        /// </summary>
        public static string MISA_Error_User_DuplicateFiled {
            get {
                return ResourceManager.GetString("MISA.Error.User.DuplicateFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn không đúng định dạng bắt buộc.
        /// </summary>
        public static string MISA_Error_User_InvalidField {
            get {
                return ResourceManager.GetString("MISA.Error.User.InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được để trống những trường bắt buộc.
        /// </summary>
        public static string MISA_Error_User_NullField {
            get {
                return ResourceManager.GetString("MISA.Error.User.NullField", resourceCulture);
            }
        }
    }
}
